"""GitHub API service layer for PRism platform setup.

Handles workflow file injection using a user-provided PAT.
Has zero imports from agents/, mcp_servers/, or foundry/.
"""

from __future__ import annotations

import base64
import os
from typing import Optional

import httpx

# ---------------------------------------------------------------------------
# Workflow template — a copy of prism-gate.yml with PRISM_URL parameterised
# ---------------------------------------------------------------------------

WORKFLOW_TEMPLATE = """\
name: PRism Gate
# ──────────────────────────────────────────────────────────────────
# Zero-setup AI risk gate — no Python, no dependencies, no checkout.
# Auto-installed by the PRism Setup Wizard.
#
# Required secret (repo Settings → Secrets → Actions):
#   GH_PAT  — a GitHub PAT with repo scope (read + write PRs/issues)
# ──────────────────────────────────────────────────────────────────

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  prism-gate:
    runs-on: ubuntu-latest

    steps:
      - name: Run PRism analysis
        id: prism
        uses: actions/github-script@v7
        env:
          PRISM_URL: ${{{{ vars.PRISM_URL || '{orchestrator_url}' }}}}
          GH_PAT: ${{{{ secrets.GH_PAT }}}}
        with:
          script: |
            const pr       = context.payload.pull_request;
            const repo     = context.repo.owner + '/' + context.repo.repo;
            const clientId = `gha-${{context.repo.owner}}-${{context.repo.repo}}`;

            // Fetch the PR diff to pass to PRism
            let diff = '';
            try {{
              const diffResp = await fetch(
                `https://api.github.com/repos/${{repo}}/pulls/${{pr.number}}`,
                {{ headers: {{ Authorization: `Bearer ${{process.env.GH_PAT}}`,
                             Accept: 'application/vnd.github.v3.diff' }} }}
              );
              if (diffResp.ok) diff = await diffResp.text();
            }} catch (_) {{}}

            // Fetch changed file list
            let changedFiles = [];
            try {{
              const filesResp = await fetch(
                `https://api.github.com/repos/${{repo}}/pulls/${{pr.number}}/files?per_page=100`,
                {{ headers: {{ Authorization: `Bearer ${{process.env.GH_PAT}}`,
                             Accept: 'application/vnd.github+json' }} }}
              );
              if (filesResp.ok) {{
                const files = await filesResp.json();
                changedFiles = files.map(f => f.filename);
              }}
            }} catch (_) {{}}

            // Call the live PRism endpoint
            const resp = await fetch(`${{process.env.PRISM_URL}}/analyze`, {{
              method: 'POST',
              headers: {{
                'Content-Type': 'application/json',
                'X-Client-ID': clientId,
              }},
              body: JSON.stringify({{
                pr_number:     pr.number,
                repo:          repo,
                changed_files: changedFiles,
                diff:          diff,
                timestamp:     new Date().toISOString(),
              }}),
            }});

            if (!resp.ok) {{
              core.setFailed(`PRism returned HTTP ${{resp.status}}`);
              return;
            }}

            const verdict = await resp.json();
            core.setOutput('decision',         verdict.decision);
            core.setOutput('confidence_score', String(verdict.confidence_score));

            // Build PR comment
            const tag    = verdict.decision === 'greenlight' ? '✅ GREENLIGHT' : '🚫 BLOCKED';
            const score  = verdict.confidence_score;
            const emojis = {{ pass: '✅', warning: '⚠️', critical: '🚫' }};

            let table = '| Agent | Status | Risk | Key Finding |\\n|-------|--------|------|-------------|\\n';
            for (const r of (verdict.agent_results || [])) {{
              const e    = emojis[r.status] || '❓';
              const find = (r.findings?.[0] || '—').substring(0, 80);
              table += `| ${{r.agent_name}} | ${{e}} ${{r.status}} | ${{r.risk_score_modifier}} | ${{find}} |\\n`;
            }}

            let body = `## PRism Deployment Risk Analysis\\n\\n**Verdict:** ${{tag}} &nbsp;|&nbsp; **Confidence Score:** \\`${{score}} / 100\\`\\n\\n${{table}}`;

            if (verdict.risk_brief) {{
              body += `\\n<details><summary>📋 Full Risk Brief</summary>\\n\\n${{verdict.risk_brief}}\\n\\n</details>`;
            }}
            if (verdict.rollback_playbook) {{
              body += `\\n\\n<details><summary>🔄 Rollback Playbook</summary>\\n\\n${{verdict.rollback_playbook}}\\n\\n</details>`;
            }}
            body += `\\n\\n---\\n*Generated by [PRism](https://github.com/soni-ishan/PRism)*`;

            // Post comment on the PR
            await github.rest.issues.createComment({{
              owner:        context.repo.owner,
              repo:         context.repo.repo,
              issue_number: pr.number,
              body,
            }});

      - name: Block merge if verdict is blocked
        if: steps.prism.outputs.decision == 'blocked'
        run: |
          echo "PRism score: ${{{{ steps.prism.outputs.confidence_score }}}} — BLOCKED"
          exit 1
"""

WORKFLOW_PATH = ".github/workflows/prism-gate.yml"
GITHUB_API_BASE = "https://api.github.com"


def _default_orchestrator_url() -> str:
    return os.getenv(
        "PRISM_ORCHESTRATOR_URL",
        "https://prism-dev-orchestrator.politerock-2dda79e7.eastus2.azurecontainerapps.io",
    )


def build_workflow_content(orchestrator_url: Optional[str] = None) -> str:
    """Render the workflow template with the given orchestrator URL."""
    url = orchestrator_url or _default_orchestrator_url()
    return WORKFLOW_TEMPLATE.format(orchestrator_url=url)


def _auth_header(token: str) -> str:
    """Return the correct Authorization value for the token type.

    GitHub accepts 'Bearer' for all modern token types (OAuth, PAT,
    installation tokens, fine-grained PATs).
    """
    return f"Bearer {token}"


async def _bootstrap_empty_repo(
    client: httpx.AsyncClient,
    headers: dict,
    owner: str,
    repo: str,
    branch: str,
) -> None:
    """Create an initial commit with a README so the Contents API works.

    The GitHub Contents API returns 404 on PUT when a repo has zero commits.
    This uses the low-level Git Data API (create blob → create tree → create
    commit → create ref) to bootstrap the default branch.
    """
    print(f"[DEBUG] Repo is empty — bootstrapping default branch '{branch}'")

    api = f"{GITHUB_API_BASE}/repos/{owner}/{repo}/git"

    # 1. Create a blob with minimal README content
    blob_resp = await client.post(
        f"{api}/blobs",
        headers=headers,
        json={"content": f"# {repo}\n", "encoding": "utf-8"},
    )
    blob_resp.raise_for_status()
    blob_sha = blob_resp.json()["sha"]

    # 2. Create a tree containing the blob
    tree_resp = await client.post(
        f"{api}/trees",
        headers=headers,
        json={
            "tree": [
                {"path": "README.md", "mode": "100644", "type": "blob", "sha": blob_sha}
            ]
        },
    )
    tree_resp.raise_for_status()
    tree_sha = tree_resp.json()["sha"]

    # 3. Create a commit pointing to the tree (no parents — initial commit)
    commit_resp = await client.post(
        f"{api}/commits",
        headers=headers,
        json={
            "message": "Initial commit",
            "tree": tree_sha,
            "parents": [],
        },
    )
    commit_resp.raise_for_status()
    commit_sha = commit_resp.json()["sha"]

    # 4. Create the default branch ref
    ref_resp = await client.post(
        f"{api}/refs",
        headers=headers,
        json={"ref": f"refs/heads/{branch}", "sha": commit_sha},
    )
    ref_resp.raise_for_status()
    print(f"[DEBUG] Bootstrapped '{branch}' with initial commit {commit_sha[:8]}")


    ref_resp.raise_for_status()
    print(f"[DEBUG] Bootstrapped '{branch}' with initial commit {commit_sha[:8]}")


async def _commit_file_via_git_api(
    client: httpx.AsyncClient,
    headers: dict,
    owner: str,
    repo: str,
    branch: str,
    path: str,
    content: str,
    message: str,
) -> dict:
    """Create or update a file using the low-level Git Data API.

    This is more reliable than the Contents API and works even when the
    Contents API returns unexpected 404s (e.g. certain OAuth token types).
    Flow:  get HEAD → get base tree → create blob → create tree → create
    commit → update ref.
    """
    api = f"{GITHUB_API_BASE}/repos/{owner}/{repo}/git"

    # 1. Get current HEAD commit SHA on the branch
    ref_resp = await client.get(
        f"{api}/ref/heads/{branch}", headers=headers,
    )
    ref_resp.raise_for_status()
    head_sha = ref_resp.json()["object"]["sha"]
    print(f"[DEBUG] Git API: HEAD={head_sha[:8]}")

    # 2. Get the tree SHA of that commit
    commit_resp = await client.get(
        f"{api}/commits/{head_sha}", headers=headers,
    )
    commit_resp.raise_for_status()
    base_tree_sha = commit_resp.json()["tree"]["sha"]

    # 3. Create a blob with the file content
    blob_resp = await client.post(
        f"{api}/blobs", headers=headers,
        json={"content": content, "encoding": "utf-8"},
    )
    blob_resp.raise_for_status()
    blob_sha = blob_resp.json()["sha"]

    # 4. Create a new tree that adds/replaces the file
    tree_resp = await client.post(
        f"{api}/trees", headers=headers,
        json={
            "base_tree": base_tree_sha,
            "tree": [
                {"path": path, "mode": "100644", "type": "blob", "sha": blob_sha}
            ],
        },
    )
    tree_resp.raise_for_status()
    new_tree_sha = tree_resp.json()["sha"]

    # 5. Create a new commit
    new_commit_resp = await client.post(
        f"{api}/commits", headers=headers,
        json={
            "message": message,
            "tree": new_tree_sha,
            "parents": [head_sha],
        },
    )
    new_commit_resp.raise_for_status()
    new_commit_sha = new_commit_resp.json()["sha"]

    # 6. Update the branch ref to point to the new commit
    update_ref_resp = await client.patch(
        f"{api}/refs/heads/{branch}", headers=headers,
        json={"sha": new_commit_sha},
    )
    update_ref_resp.raise_for_status()

    commit_data = new_commit_resp.json()
    print(f"[DEBUG] Git API: committed {new_commit_sha[:8]} on {branch}")
    return {
        "content": {"path": path},
        "commit": {
            "sha": new_commit_sha,
            "html_url": commit_data.get("html_url", ""),
        },
    }


async def commit_workflow_file(
    token: str,
    owner: str,
    repo: str,
    orchestrator_url: Optional[str] = None,
) -> dict:
    """Create or update the PRism workflow file in the target repository.

    Uses the GitHub Contents API to commit .github/workflows/prism-gate.yml.
    Returns the API response dict.
    """
    content = build_workflow_content(orchestrator_url)
    encoded = base64.b64encode(content.encode()).decode()

    headers = {
        "Authorization": _auth_header(token),
        "Accept": "application/vnd.github+json",
        "User-Agent": "PRism-Setup-Platform",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    url = f"{GITHUB_API_BASE}/repos/{owner}/{repo}/contents/{WORKFLOW_PATH}"

    async with httpx.AsyncClient() as client:
        # First, verify the token's scopes include repo write access
        scope_resp = await client.get(
            f"{GITHUB_API_BASE}/user",
            headers=headers,
        )
        scopes = scope_resp.headers.get("x-oauth-scopes", "")
        github_user = scope_resp.json().get("login", "unknown") if scope_resp.status_code == 200 else "unknown"
        print(f"[DEBUG] Token scopes: {scopes}")
        print(f"[DEBUG] Authenticated as: {github_user}")

        # Verify the repo exists and the token has push access
        default_branch = "main"
        repo_resp = await client.get(
            f"{GITHUB_API_BASE}/repos/{owner}/{repo}",
            headers=headers,
        )
        print(f"[DEBUG] Repo check: {repo_resp.status_code}")
        if repo_resp.status_code == 404:
            raise PermissionError(
                f"Repository '{owner}/{repo}' not found. Either the repo does not exist "
                f"or the authenticated user ({github_user}) does not have access to it. "
                f"Make sure the repo exists and the GitHub account you signed in with has push access."
            )
        if repo_resp.status_code == 200:
            repo_data = repo_resp.json()
            permissions = repo_data.get("permissions", {})
            print(f"[DEBUG] Repo permissions: {permissions}")
            if not permissions.get("push"):
                raise PermissionError(
                    f"The authenticated user ({github_user}) does not have write/push access "
                    f"to '{owner}/{repo}'. Please ensure this account has push permissions "
                    f"(admin, maintain, or write role) on the repository."
                )
            # GitHub Contents API cannot create files in repos with no commits.
            # We detect this reactively below (PUT returns 404) and bootstrap.
            default_branch = repo_data.get("default_branch", "main")
            print(f"[DEBUG] Default branch: {default_branch}, size: {repo_data.get('size')}")

        # Check if file already exists to get its SHA (required for updates)
        existing_sha: Optional[str] = None
        get_resp = await client.get(url, headers=headers)
        print(f"[DEBUG] GET existing file: {get_resp.status_code}")
        if get_resp.status_code == 200:
            existing_sha = get_resp.json().get("sha")

        body: dict = {
            "message": "ci: add PRism deployment risk gate workflow",
            "content": encoded,
            "branch": default_branch,
        }
        if existing_sha:
            body["sha"] = existing_sha
            body["message"] = "ci: update PRism deployment risk gate workflow"

        print(f"[DEBUG] PUT body keys: {list(body.keys())}, branch={default_branch}")
        put_resp = await client.put(url, headers=headers, json=body)
        print(f"[DEBUG] PUT status: {put_resp.status_code}")

        if put_resp.is_success:
            return put_resp.json()

        # ── Contents API failed — fall back to the Git Data API ──
        print(f"[DEBUG] Contents API PUT failed ({put_resp.status_code}): {put_resp.text}")
        print(f"[DEBUG] Falling back to Git Data API…")

        message = "ci: update PRism deployment risk gate workflow" if existing_sha else "ci: add PRism deployment risk gate workflow"

        # If repo is truly empty (no default branch), bootstrap it first
        if put_resp.status_code == 404:
            try:
                await _bootstrap_empty_repo(client, headers, owner, repo, default_branch)
            except Exception:
                pass  # 422 = branch exists = repo not empty, continue

        return await _commit_file_via_git_api(
            client=client,
            headers=headers,
            owner=owner,
            repo=repo,
            branch=default_branch,
            path=WORKFLOW_PATH,
            content=content,
            message=message,
        )


async def check_workflow_exists(token: str, owner: str, repo: str) -> bool:
    """Return True if prism-gate.yml already exists in the target repository."""
    headers = {
        "Authorization": _auth_header(token),
        "Accept": "application/vnd.github+json",
    }
    url = f"{GITHUB_API_BASE}/repos/{owner}/{repo}/contents/{WORKFLOW_PATH}"

    async with httpx.AsyncClient() as client:
        resp = await client.get(url, headers=headers)
        return resp.status_code == 200


async def check_secret_configured(token: str, owner: str, repo: str, secret_name: str) -> bool:
    """Return True if the named Actions secret exists in the repository.

    Note: GitHub does not expose secret values — only whether a secret exists.
    """
    headers = {
        "Authorization": _auth_header(token),
        "Accept": "application/vnd.github+json",
    }
    url = f"{GITHUB_API_BASE}/repos/{owner}/{repo}/actions/secrets/{secret_name}"

    async with httpx.AsyncClient() as client:
        resp = await client.get(url, headers=headers)
        return resp.status_code == 200
